apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab
  namespace: devops-tools
spec:
  generators:
  - list:
      elements:
      - name: arcrunners
        repo: https://github.com/home-kops/k8s-devops-tools.git
        path: ./arcrunners
        namespace: devops-tools
      - name: argocd
        repo: https://github.com/home-kops/k8s-devops-tools.git
        path: ./argocd
        namespace: devops-tools
      - name: renovate
        repo: https://github.com/home-kops/k8s-devops-tools.git
        path: ./renovate
        namespace: devops-tools
      - name: jellyfin
        repo: https://github.com/home-kops/k8s-media.git
        path: ./jellyfin
        namespace: media
      - name: cwa
        repo: https://github.com/home-kops/k8s-media.git
        path: ./cwa
        namespace: media
      - name: cwa-downloader
        repo: https://github.com/home-kops/k8s-media.git
        path: ./cwa-downloader
        namespace: media
      - name: homepage
        repo: https://github.com/home-kops/k8s-misc.git
        path: ./homepage
        namespace: misc
      - name: alloy
        repo: https://github.com/home-kops/k8s-monitoring.git
        path: ./alloy
        namespace: monitoring
      - name: crowdsec
        repo: https://github.com/home-kops/k8s-monitoring.git
        path: ./crowdsec
        namespace: monitoring
      - name: grafana
        repo: https://github.com/home-kops/k8s-monitoring.git
        path: ./grafana
        namespace: monitoring
      - name: loki
        repo: https://github.com/home-kops/k8s-monitoring.git
        path: ./loki
        namespace: monitoring
      - name: prometheus
        repo: https://github.com/home-kops/k8s-monitoring.git
        path: ./prometheus
        namespace: monitoring
      - name: tempo
        repo: https://github.com/home-kops/k8s-monitoring.git
        path: ./tempo
        namespace: monitoring
      - name: traefik
        repo: https://github.com/home-kops/k8s-network.git
        path: ./traefik
        namespace: network
      - name: certmanager
        repo: https://github.com/home-kops/k8s-network.git
        path: ./certmanager
        namespace: network
      - name: metallb
        repo: https://github.com/home-kops/k8s-network.git
        path: ./metallb
        namespace: network
      - name: jackett
        repo: https://github.com/home-kops/k8s-p2p.git
        path: ./jackett
        namespace: p2p
      - name: slskd
        repo: https://github.com/home-kops/k8s-p2p.git
        path: ./slskd
        namespace: p2p
      - name: qbittorrent
        repo: https://github.com/home-kops/k8s-p2p.git
        path: ./qbittorrent
        namespace: p2p
      - name: falco
        repo: https://github.com/home-kops/k8s-sec.git
        path: ./falco
        namespace: sec
      - name: nfs-sc
        repo: https://github.com/home-kops/k8s-storage.git
        path: ./nfs
        namespace: storage
      - name: vault
        repo: https://github.com/home-kops/k8s-vault.git
        path: ./vault
        namespace: vault
      - name: unsealer
        repo: https://github.com/home-kops/k8s-vault.git
        path: ./unsealer
        namespace: vault
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repo}}'
        targetRevision: main
        path: '{{path}}'
        plugin:
          name: argocd-vault-plugin-kustomize
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
